# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1e2d8a5f0b5da850d4a5f07b55dd0770dd2e4944b27f9e142ce21489b4d345d867d6264bb4115322d3b062cdc208994280f16f3f144fffdb6f81dd452b66d44

  email_provider_username: <%= ENV["ricke2005@gmail.com"] %> 
  email_provider_password: <%= ENV["Christianewing1"] %> 
  mailchimp_api_key: <%= ENV["a31174c3246d5de593d705269d5a47de-us11"] %>
  mailchimp_list_id: <%= ENV["850871bbf4"] %> 
  #domain_name: example.com 
  owner_email: <%= ENV["ricke2005@gmail.com"] %> 

test:
  secret_key_base: 1d585bc7a1dd1260adb93c55f9391abd14598cf558fdf97f54257afe621beadc1932df61a00a3af47e56bc6d82b029439a429f9a1ce2a5e1d3a9654ac4bb7357
 
 # Do not keep production secrets in the repository, 
 # instead read values from the environment.
production: 
   
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %> 
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %> 
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %> 
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %> 
  #domain_name: <%= ENV["DOMAIN_NAME"] %> 
  owner_email: <%= ENV["OWNER_EMAIL"] %> 
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 



